stages:
  - build
  - deploy

build_master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" ./
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

# On branches except master: verify that build works, do not push to registry
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull ./
  except:
    - master

deploy:
  stage: deploy
  image: amiveth/service-update-helper
  script:
    - export CI_DEPLOY_SERVICE=$CI_DEPLOY_SERVICE_ERROR_PAGES
    - /update.py
  only:
    - master
